version: '3'
services:
  front:
    container_name: strapi
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    command: npm run develop
